### ISSUE TITLE
sending data

### ISSUE THREAD

**Issue by ndjota** [SFeli/T-Call_HotSpot#4]
Hello SFeli. 

I would like to use your code as a native router to connect other esp8266s, 
but can't get it to send mqtt data, could you help me? 

Thanks for your response.

**Comment by philo-create** [comment]
@ndjota  did  you manage to  get  it  working?

**Comment by SFeli** [comment]
Hi ndjota,
I have reworked the programm and now we have a key (in my case the "Get") just behind the ip:port.
So you can enhance this by MQTT if you like.
